nav:
  - Home:
    - index.md
  - Installation & Deployment:
    - installation/index.md
    - installation/first-install.md
    - installation/configuration.md
    - installation/securing.md
    - installation/updating.md
    - installation/troubleshooting.md
  #- Configuration:
  #  - configuration/index.md
  #  - configuration/*.md
  - Features:
    - features/index.md
    - Plot:
      - features/plot/index.md
      - features/plot/build-area-factor.md
      - features/plot/player-limit.md
      - features/plot/roles-limit.md
    - User:
      - features/user/index.md
      - features/user/plot-limit.md
    - features/feature.md
    - features/package.md
    - features/item.md
    - features/item-selector.md
    - features/locked-item.md
    - features/custom-item.md
    - features/tag.md
    - features/economy.md
    - features/amplifier.md
  - Commands:
      - commands/index.md
      - Plot Commands:
          - commands/plot/menu.md
          - commands/plot/ban.md
          - commands/plot/unban.md
          - commands/plot/kick.md
          - commands/plot/mute.md
          - commands/plot/unmute.md
          - commands/plot/banlist.md
          - commands/plot/mutelist.md
          - commands/plot/mutechat.md
          - commands/plot/tp.md
          - commands/plot/clearinv.md
          - commands/plot/vote.md
          - commands/plot/gm.md
          - commands/plot/spawn.md
          - commands/plot/setspawn.md
          - Plot Admin:
              - commands/plot/admin/build-area-factor.md
              - commands/plot/admin/player-limit.md
              - commands/plot/admin/roles-limit.md
              - commands/plot/admin/item.md
              - commands/plot/admin/vote.md
              - commands/plot/admin/feature.md
      - Housing Commands:
          - commands/housing/browse.md
          - commands/housing/search.md
          - commands/housing/profile.md
          - commands/housing/visit.md
          - commands/housing/jumpto.md
          - commands/housing/myplots.md
          - commands/housing/plot-join.md
          - commands/housing/plot-copy-id.md
          - commands/housing/callback.md
          - commands/housing/changelog.md
          - commands/housing/dynamic.md
          - commands/housing/top.md
          - commands/housing/hub.md
          - commands/housing/balance.md
          - commands/housing/pay.md
          - Housing Admin:
              - commands/housing/admin/user.md
              - commands/housing/admin/package.md
              - commands/housing/admin/plot.md
              - commands/housing/admin/economy.md
              - commands/housing/admin/tags.md
              - commands/housing/admin/reload.md
  - Guides:
    - guides/index.md
    - guides/worldedit.md
    - guides/unlockable-items.md
    - guides/custom-packages.md
    - guides/milestones.md
  - Other:
    - other/index.md
    - Config conventions:
        - other/config-conventions/price.md

  #- Modrinth: 'https://modrinth.com/plugin/decentholograms'
  #- Spigot: 'http://decentholograms.eu/'
  - Discord: 'https://discord.decentsoftware.eu/'