nav:
  - Home:
    - index.md
  - Installation & Deployment:
    - installation/index.md
    - installation/first-install.md
    - installation/configuration.md
    - installation/securing.md
    - installation/updating.md
    - installation/troubleshooting.md
  #- Commands:
  #  - commands/index.md
  #  - commands/permissions.md
  #  - commands/*.md
  #  - /dh displays:
  #    - commands/displays/*.md
  #  - /dh features:
  #    - commands/features/*.md
  #  - /dh hologram:
  #    - commands/hologram/*.md
  #  - /dh lines:
  #    - commands/hologram-lines/*.md
  #  - /dh pages:
  #    - commands/hologram-pages/*.md
  #- Configuration:
  #  - configuration/index.md
  #  - configuration/*.md
  #- Features:
  #  - features/index.md
  #  - features/actions.md
  #  - Animations:
  #    - features/animations/*.md
  #  - features/*.md
  #- Guides:
  #  - guides/index.md
  #  - guides/*.md
  #- API:
  #  - api/get-started.md
  #  - api/faq.md
  #  - Events:
  #    - api/events/*.md
  #  - api/**/*.md
  #- Modrinth: 'https://modrinth.com/plugin/decentholograms'
  #- Spigot: 'http://decentholograms.eu/'
  - Discord: 'https://discord.decentsoftware.eu/'